// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (user_id, name, keywords, subreddits, product_description, schedule_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at
`

type CreateCampaignParams struct {
	UserID             int32    `json:"user_id"`
	Name               string   `json:"name"`
	Keywords           []string `json:"keywords"`
	Subreddits         []string `json:"subreddits"`
	ProductDescription string   `json:"product_description"`
	ScheduleMinutes    int32    `json:"schedule_minutes"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.UserID,
		arg.Name,
		arg.Keywords,
		arg.Subreddits,
		arg.ProductDescription,
		arg.ScheduleMinutes,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignByIDAndUser = `-- name: GetCampaignByIDAndUser :one
SELECT id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at
FROM campaigns
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetCampaignByIDAndUserParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetCampaignByIDAndUserRow struct {
	ID                 int32              `json:"id"`
	Name               string             `json:"name"`
	Keywords           []string           `json:"keywords"`
	Subreddits         []string           `json:"subreddits"`
	ProductDescription string             `json:"product_description"`
	ScheduleMinutes    int32              `json:"schedule_minutes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCampaignByIDAndUser(ctx context.Context, arg GetCampaignByIDAndUserParams) (GetCampaignByIDAndUserRow, error) {
	row := q.db.QueryRow(ctx, getCampaignByIDAndUser, arg.ID, arg.UserID)
	var i GetCampaignByIDAndUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignsByUser = `-- name: GetCampaignsByUser :many
SELECT id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at
FROM campaigns
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetCampaignsByUserRow struct {
	ID                 int32              `json:"id"`
	Name               string             `json:"name"`
	Keywords           []string           `json:"keywords"`
	Subreddits         []string           `json:"subreddits"`
	ProductDescription string             `json:"product_description"`
	ScheduleMinutes    int32              `json:"schedule_minutes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCampaignsByUser(ctx context.Context, userID int32) ([]GetCampaignsByUserRow, error) {
	rows, err := q.db.Query(ctx, getCampaignsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignsByUserRow
	for rows.Next() {
		var i GetCampaignsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Keywords,
			&i.Subreddits,
			&i.ProductDescription,
			&i.ScheduleMinutes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
