// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"
)

const getDueJobs = `-- name: GetDueJobs :many
SELECT j.id, j.status, c.id AS campaign_id, c.subreddits, c.keywords, c.schedule_minutes 
FROM jobs j
JOIN campaigns c ON c.id = j.campaign_id
WHERE j.next_run_at <= NOW() AND j.status != 'running' AND c.active = true
`

type GetDueJobsRow struct {
	ID              int32    `json:"id"`
	Status          string   `json:"status"`
	CampaignID      int32    `json:"campaign_id"`
	Subreddits      []string `json:"subreddits"`
	Keywords        []string `json:"keywords"`
	ScheduleMinutes int32    `json:"schedule_minutes"`
}

func (q *Queries) GetDueJobs(ctx context.Context) ([]GetDueJobsRow, error) {
	rows, err := q.db.Query(ctx, getDueJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueJobsRow
	for rows.Next() {
		var i GetDueJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CampaignID,
			&i.Subreddits,
			&i.Keywords,
			&i.ScheduleMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initializeJobs = `-- name: InitializeJobs :exec
INSERT INTO jobs (campaign_id, status)
SELECT id, 'pending' FROM campaigns WHERE active = true
ON CONFLICT (campaign_id) DO NOTHING
`

func (q *Queries) InitializeJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initializeJobs)
	return err
}

const setJobRunning = `-- name: SetJobRunning :exec
UPDATE jobs SET status = 'running', updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetJobRunning(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setJobRunning, id)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs 
SET status = $1, error = $2, last_run_at = NOW(), next_run_at = NOW() + ($3::int * interval '1 minute'), updated_at = NOW()
WHERE id = $4
`

type UpdateJobStatusParams struct {
	Status  string `json:"status"`
	Error   string `json:"error"`
	Column3 int32  `json:"column_3"`
	ID      int32  `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.Status,
		arg.Error,
		arg.Column3,
		arg.ID,
	)
	return err
}
