// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID                 int32              `json:"id"`
	UserID             int32              `json:"user_id"`
	Name               string             `json:"name"`
	Keywords           []string           `json:"keywords"`
	Subreddits         []string           `json:"subreddits"`
	ProductDescription string             `json:"product_description"`
	ScheduleMinutes    int32              `json:"schedule_minutes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID         int32              `json:"id"`
	CampaignID int32              `json:"campaign_id"`
	Status     string             `json:"status"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
	Error      string             `json:"error"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RawPost struct {
	ID           int32              `json:"id"`
	CampaignID   int32              `json:"campaign_id"`
	RedditPostID string             `json:"reddit_post_id"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Author       string             `json:"author"`
	Subreddit    string             `json:"subreddit"`
	Url          string             `json:"url"`
	Upvotes      int32              `json:"upvotes"`
	CommentCount int32              `json:"comment_count"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Plan         string             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
