// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetCampaignByIDAndUser(ctx context.Context, arg GetCampaignByIDAndUserParams) (GetCampaignByIDAndUserRow, error)
	GetCampaignPosts(ctx context.Context, arg GetCampaignPostsParams) ([]GetCampaignPostsRow, error)
	GetCampaignsByUser(ctx context.Context, userID int32) ([]GetCampaignsByUserRow, error)
	GetDueJobs(ctx context.Context) ([]GetDueJobsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InitializeJobs(ctx context.Context) error
	InsertRawPost(ctx context.Context, arg InsertRawPostParams) (int64, error)
	SetJobRunning(ctx context.Context, id int32) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
}

var _ Querier = (*Queries)(nil)
