// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_posts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCampaignPosts = `-- name: GetCampaignPosts :many
SELECT p.id, p.reddit_post_id, p.title, p.body, p.author, p.subreddit, p.url, p.upvotes, p.comment_count, p.posted_at
FROM raw_posts p
JOIN campaigns c ON p.campaign_id = c.id
WHERE p.campaign_id = $1 AND c.user_id = $2
ORDER BY p.posted_at DESC LIMIT $3
`

type GetCampaignPostsParams struct {
	CampaignID int32 `json:"campaign_id"`
	UserID     int32 `json:"user_id"`
	Limit      int32 `json:"limit"`
}

type GetCampaignPostsRow struct {
	ID           int32              `json:"id"`
	RedditPostID string             `json:"reddit_post_id"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Author       string             `json:"author"`
	Subreddit    string             `json:"subreddit"`
	Url          string             `json:"url"`
	Upvotes      int32              `json:"upvotes"`
	CommentCount int32              `json:"comment_count"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) GetCampaignPosts(ctx context.Context, arg GetCampaignPostsParams) ([]GetCampaignPostsRow, error) {
	rows, err := q.db.Query(ctx, getCampaignPosts, arg.CampaignID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignPostsRow
	for rows.Next() {
		var i GetCampaignPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.RedditPostID,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Subreddit,
			&i.Url,
			&i.Upvotes,
			&i.CommentCount,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRawPost = `-- name: InsertRawPost :execrows
INSERT INTO raw_posts (campaign_id, reddit_post_id, title, body, author, subreddit, url, upvotes, comment_count, posted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (campaign_id, reddit_post_id) DO NOTHING
`

type InsertRawPostParams struct {
	CampaignID   int32              `json:"campaign_id"`
	RedditPostID string             `json:"reddit_post_id"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Author       string             `json:"author"`
	Subreddit    string             `json:"subreddit"`
	Url          string             `json:"url"`
	Upvotes      int32              `json:"upvotes"`
	CommentCount int32              `json:"comment_count"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) InsertRawPost(ctx context.Context, arg InsertRawPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawPost,
		arg.CampaignID,
		arg.RedditPostID,
		arg.Title,
		arg.Body,
		arg.Author,
		arg.Subreddit,
		arg.Url,
		arg.Upvotes,
		arg.CommentCount,
		arg.PostedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
