// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID                 int32
	UserID             int32
	Name               string
	Keywords           []string
	Subreddits         []string
	ProductDescription string
	ScheduleMinutes    int32
	Active             bool
	CreatedAt          pgtype.Timestamptz
	MinUpvotes         int32
	MinComments        int32
	MaxAgeDays         int32
}

type Job struct {
	ID         int32
	CampaignID int32
	Status     string
	LastRunAt  pgtype.Timestamptz
	NextRunAt  pgtype.Timestamptz
	Error      string
	UpdatedAt  pgtype.Timestamptz
}

type RawPost struct {
	ID           int32
	CampaignID   int32
	RedditPostID string
	Title        string
	Body         string
	Author       string
	Subreddit    string
	Url          string
	Upvotes      int32
	CommentCount int32
	PostedAt     pgtype.Timestamptz
	FetchedAt    pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Plan         string
	CreatedAt    pgtype.Timestamptz
}
