// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', updated_at = NOW()
WHERE id = (
    SELECT j.id
    FROM jobs j
    JOIN campaigns c ON c.id = j.campaign_id
    WHERE j.next_run_at <= NOW()
    AND j.status != 'running'
    AND c.active = true
    ORDER BY j.next_run_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, campaign_id
`

type ClaimJobRow struct {
	ID         int32
	CampaignID int32
}

func (q *Queries) ClaimJob(ctx context.Context) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i ClaimJobRow
	err := row.Scan(&i.ID, &i.CampaignID)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (user_id, name, keywords, subreddits, product_description, schedule_minutes, active, min_upvotes, min_comments, max_age_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at, min_upvotes, min_comments, max_age_days
`

type CreateCampaignParams struct {
	UserID             int32
	Name               string
	Keywords           []string
	Subreddits         []string
	ProductDescription string
	ScheduleMinutes    int32
	Active             bool
	MinUpvotes         int32
	MinComments        int32
	MaxAgeDays         int32
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.UserID,
		arg.Name,
		arg.Keywords,
		arg.Subreddits,
		arg.ProductDescription,
		arg.ScheduleMinutes,
		arg.Active,
		arg.MinUpvotes,
		arg.MinComments,
		arg.MaxAgeDays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.MinUpvotes,
		&i.MinComments,
		&i.MaxAgeDays,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (campaign_id, status, next_run_at)
VALUES ($1, $2, $3)
ON CONFLICT (campaign_id) DO NOTHING
RETURNING id, campaign_id, status, last_run_at, next_run_at, error, updated_at
`

type CreateJobParams struct {
	CampaignID int32
	Status     string
	NextRunAt  pgtype.Timestamptz
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.CampaignID, arg.Status, arg.NextRunAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const createRawPost = `-- name: CreateRawPost :exec
INSERT INTO raw_posts (campaign_id, reddit_post_id, title, body, author, subreddit, url, upvotes, comment_count, posted_at)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
WHERE NOT EXISTS (
    SELECT 1 FROM raw_posts 
    WHERE campaign_id = $1 AND (reddit_post_id = $2 OR (title = $3 AND author = $5))
)
`

type CreateRawPostParams struct {
	CampaignID   int32
	RedditPostID string
	Title        string
	Body         string
	Author       string
	Subreddit    string
	Url          string
	Upvotes      int32
	CommentCount int32
	PostedAt     pgtype.Timestamptz
}

func (q *Queries) CreateRawPost(ctx context.Context, arg CreateRawPostParams) error {
	_, err := q.db.Exec(ctx, createRawPost,
		arg.CampaignID,
		arg.RedditPostID,
		arg.Title,
		arg.Body,
		arg.Author,
		arg.Subreddit,
		arg.Url,
		arg.Upvotes,
		arg.CommentCount,
		arg.PostedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, plan)
VALUES ($1, $2)
RETURNING id, email, plan, created_at
`

type CreateUserParams struct {
	Email string
	Plan  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1 AND user_id = $2
`

type DeleteCampaignParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.Exec(ctx, deleteCampaign, arg.ID, arg.UserID)
	return err
}

const deleteRawPost = `-- name: DeleteRawPost :exec
DELETE FROM raw_posts
WHERE raw_posts.id = $1 AND raw_posts.campaign_id IN (
    SELECT campaigns.id FROM campaigns WHERE campaigns.user_id = $2
)
`

type DeleteRawPostParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteRawPost(ctx context.Context, arg DeleteRawPostParams) error {
	_, err := q.db.Exec(ctx, deleteRawPost, arg.ID, arg.UserID)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, user_id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at, min_upvotes, min_comments, max_age_days FROM campaigns
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCampaignParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.ID, arg.UserID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.MinUpvotes,
		&i.MinComments,
		&i.MaxAgeDays,
	)
	return i, err
}

const getCampaignWithJob = `-- name: GetCampaignWithJob :one
SELECT j.id, j.campaign_id, j.status, j.last_run_at, j.next_run_at, j.error, j.updated_at, c.name, c.keywords, c.subreddits, c.product_description, c.schedule_minutes, c.min_upvotes, c.min_comments, c.max_age_days
FROM jobs j
JOIN campaigns c ON c.id = j.campaign_id
WHERE j.id = $1
`

type GetCampaignWithJobRow struct {
	ID                 int32
	CampaignID         int32
	Status             string
	LastRunAt          pgtype.Timestamptz
	NextRunAt          pgtype.Timestamptz
	Error              string
	UpdatedAt          pgtype.Timestamptz
	Name               string
	Keywords           []string
	Subreddits         []string
	ProductDescription string
	ScheduleMinutes    int32
	MinUpvotes         int32
	MinComments        int32
	MaxAgeDays         int32
}

func (q *Queries) GetCampaignWithJob(ctx context.Context, id int32) (GetCampaignWithJobRow, error) {
	row := q.db.QueryRow(ctx, getCampaignWithJob, id)
	var i GetCampaignWithJobRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Error,
		&i.UpdatedAt,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.MinUpvotes,
		&i.MinComments,
		&i.MaxAgeDays,
	)
	return i, err
}

const getJobByCampaignID = `-- name: GetJobByCampaignID :one
SELECT id, campaign_id, status, last_run_at, next_run_at, error, updated_at FROM jobs
WHERE campaign_id = $1
`

func (q *Queries) GetJobByCampaignID(ctx context.Context, campaignID int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByCampaignID, campaignID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Status,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const getRawPostWithCampaign = `-- name: GetRawPostWithCampaign :many
SELECT rp.id, rp.title, rp.body, rp.campaign_id, c.product_description
FROM raw_posts rp
JOIN campaigns c ON c.id = rp.campaign_id
WHERE rp.id = $1 AND c.user_id = $2
LIMIT 1
`

type GetRawPostWithCampaignParams struct {
	ID     int32
	UserID int32
}

type GetRawPostWithCampaignRow struct {
	ID                 int32
	Title              string
	Body               string
	CampaignID         int32
	ProductDescription string
}

func (q *Queries) GetRawPostWithCampaign(ctx context.Context, arg GetRawPostWithCampaignParams) ([]GetRawPostWithCampaignRow, error) {
	rows, err := q.db.Query(ctx, getRawPostWithCampaign, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRawPostWithCampaignRow
	for rows.Next() {
		var i GetRawPostWithCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CampaignID,
			&i.ProductDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, plan, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaignsByUser = `-- name: ListCampaignsByUser :many
SELECT id, user_id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at, min_upvotes, min_comments, max_age_days FROM campaigns
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCampaignsByUser(ctx context.Context, userID int32) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Keywords,
			&i.Subreddits,
			&i.ProductDescription,
			&i.ScheduleMinutes,
			&i.Active,
			&i.CreatedAt,
			&i.MinUpvotes,
			&i.MinComments,
			&i.MaxAgeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByCampaign = `-- name: ListPostsByCampaign :many
SELECT id, campaign_id, reddit_post_id, title, body, author, subreddit, url, upvotes, comment_count, posted_at, fetched_at, score, category, ai_summary, is_lead FROM raw_posts
WHERE campaign_id = $1
ORDER BY posted_at DESC
`

func (q *Queries) ListPostsByCampaign(ctx context.Context, campaignID int32) ([]RawPost, error) {
	rows, err := q.db.Query(ctx, listPostsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawPost
	for rows.Next() {
		var i RawPost
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.RedditPostID,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Subreddit,
			&i.Url,
			&i.Upvotes,
			&i.CommentCount,
			&i.PostedAt,
			&i.FetchedAt,
			&i.Score,
			&i.Category,
			&i.AiSummary,
			&i.IsLead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorizedPosts = `-- name: ListUncategorizedPosts :many
SELECT id, campaign_id, reddit_post_id, title, body, author, subreddit, url, upvotes, comment_count, posted_at, fetched_at, score, category, ai_summary, is_lead FROM raw_posts
WHERE campaign_id = $1 AND (category = '' OR category = 'error')
LIMIT 50
`

func (q *Queries) ListUncategorizedPosts(ctx context.Context, campaignID int32) ([]RawPost, error) {
	rows, err := q.db.Query(ctx, listUncategorizedPosts, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawPost
	for rows.Next() {
		var i RawPost
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.RedditPostID,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Subreddit,
			&i.Url,
			&i.Upvotes,
			&i.CommentCount,
			&i.PostedAt,
			&i.FetchedAt,
			&i.Score,
			&i.Category,
			&i.AiSummary,
			&i.IsLead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET keywords = $2, product_description = $3, schedule_minutes = $4, min_upvotes = $6, min_comments = $7, max_age_days = $8
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, name, keywords, subreddits, product_description, schedule_minutes, active, created_at, min_upvotes, min_comments, max_age_days
`

type UpdateCampaignParams struct {
	ID                 int32
	Keywords           []string
	ProductDescription string
	ScheduleMinutes    int32
	UserID             int32
	MinUpvotes         int32
	MinComments        int32
	MaxAgeDays         int32
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Keywords,
		arg.ProductDescription,
		arg.ScheduleMinutes,
		arg.UserID,
		arg.MinUpvotes,
		arg.MinComments,
		arg.MaxAgeDays,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Keywords,
		&i.Subreddits,
		&i.ProductDescription,
		&i.ScheduleMinutes,
		&i.Active,
		&i.CreatedAt,
		&i.MinUpvotes,
		&i.MinComments,
		&i.MaxAgeDays,
	)
	return i, err
}

const updateCampaignActiveStatus = `-- name: UpdateCampaignActiveStatus :exec
UPDATE campaigns
SET active = $2
WHERE id = $1 AND user_id = $3
`

type UpdateCampaignActiveStatusParams struct {
	ID     int32
	Active bool
	UserID int32
}

func (q *Queries) UpdateCampaignActiveStatus(ctx context.Context, arg UpdateCampaignActiveStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignActiveStatus, arg.ID, arg.Active, arg.UserID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs 
SET status = $1, error = $2, last_run_at = $3, next_run_at = $4, updated_at = NOW()
WHERE id = $5
`

type UpdateJobStatusParams struct {
	Status    string
	Error     string
	LastRunAt pgtype.Timestamptz
	NextRunAt pgtype.Timestamptz
	ID        int32
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.Status,
		arg.Error,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.ID,
	)
	return err
}

const updatePostAIFields = `-- name: UpdatePostAIFields :exec
UPDATE raw_posts
SET score = $2, category = $3, ai_summary = $4, is_lead = $5
WHERE id = $1
`

type UpdatePostAIFieldsParams struct {
	ID        int32
	Score     int32
	Category  string
	AiSummary string
	IsLead    bool
}

func (q *Queries) UpdatePostAIFields(ctx context.Context, arg UpdatePostAIFieldsParams) error {
	_, err := q.db.Exec(ctx, updatePostAIFields,
		arg.ID,
		arg.Score,
		arg.Category,
		arg.AiSummary,
		arg.IsLead,
	)
	return err
}
